var users = ['Rachel','Chandler','Ross','Monica'];

var script = [ { user: 0, text: 'Okay, Chandler!' },
  { user: 1, text: 'Okay.' },
  { user: 0,
    text: 'And your horoscope says, "On the fifth a special someone is going to give you a gift."' },
  { user: 1, text: '' },
  { user: 0, text: 'Op, but the twelfth brings a lover’s spat.' },
  { user: 3,
    text: ' You are going to make a joke about my special present! Why would you do that?!' },
  { user: 0,
    text: 'Oh, wait and on the nineteenth a secret crush announces itself.' },
  { user: 1, text: 'Hey!!' },
  { user: 0,
    text: ' Oh my God! It’s Joey Tribbiani of Mac and C.H.E.E.S.E.!!!!!!!' },
  { user: 1,
    text: 'Oh that’s right. It’s your first day! So are you psyched to fight fake crime with your robot sidekick?' },
  { user: 3,
    text: 'I think our lover’s spat will start a little early this month.' },
  { user: 1,
    text: 'Are you judging them by their covers? Because you’re really not supposed to do that.' },
  { user: 0,
    text: 'Be-because the last one was such a big seller?' },
  { user: 2, text: ' Hey!' },
  { user: 1, text: 'Hey!' },
  { user: 0, text: 'Hey!' },
  { user: 2, text: 'What are you guys doing later?' },
  { user: 0, text: ' We do?' },
  { user: 0, text: 'Okay.' },
  { user: 2,
    text: ' I just found out that Elizabeth’s dad wants to meet me.' },
  { user: 1,
    text: 'Wait a minute, hold the phone! You’re not Elizabeth’s dad?!' },
  { user: 2,
    text: 'Come on guys, I-I really want this guy to like me. It-it would really help me out if you guys were here to make me look good.' },
  { user: 2, text: 'Thanks!' },
  { user: 3,
    text: 'We know how tough those parent/teacher conferences can be.' },
  { user: 2, text: 'It-it’s great to meet you Paul.' },
  { user: 2, text: 'Of course, of course, Mr. Stevens.' },
  { user: 2, text: 'Eh-wh—Excuse me?' },
  { user: 2, text: 'That’s funny. Umm….  It’s not funny.' },
  { user: 2,
    text: 'Okay. I can, I can see that. Umm, but I think if you give me umm, one chance I can, I can change your mind.' },
  { user: 2, text: 'What?' },
  { user: 2, text: 'This is—you—' },
  { user: 2,
    text: 'Okay, umm I want you to know that I have never done anything like this before. I mean, I mean I’ve been in um, relationships in general, uh but I have never done it with a student—I mean I not—not it! I mean, I mean I don’t—We haven’t done it. Uh, I mean, I mean, we’ve-we’ve-we’ve done stuff.  Okay, okay, a joke, a joke—lighten the mood. Umm, two guys go into a bar. One of them is Irish.' },
  { user: 2, text: 'And the Irish guy wins the joke!' },
  { user: 3, text: 'Ross!!' },
  { user: 1, text: 'Ross!' },
  { user: 3, text: 'How crazy that we’d run into you!' },
  { user: 2,
    text: 'Oh God, thank you!  Umm, uh, Mr. Stevens I’d like you to meet my friends uh, this is Phoebe, Monica, and Chandler.' },
  { user: 3, text: ' Is-is-is there a-a Mrs. Stevens?' },
  { user: 1, text: 'There’s a Mr. Bing!' },
  { user: 2,
    text: 'Okay umm, why don’t we all take a seat, y’know? And uh, and I’ll get us all some uh some coffees—' },
  { user: 3,
    text: 'Y’know, it is so strange seeing Ross here this time of day, ‘cause usually he’s got the children’s hospital.' },
  { user: 3, text: 'And he’s a great brother!' },
  { user: 3, text: 'Ohh!' },
  { user: 1,
    text: 'But uh Ross, Ross is a great guy! I was roommates with him in college. Uh, funny story…  You’re roommate in college died didn’t he?' },
  { user: 2,
    text: ' So I hope you guys were finding something to talk about.' },
  { user: 1, text: 'Yes, we were just…' },
  { user: 0,
    text: 'Hi, I’m sorry I’m late but I am ready, ready to talk you up! When does Liz’s father get here?' },
  { user: 0, text: 'Oh! Ross is sooo great!' },
  { user: 1,
    text: 'Hey honey, you got the kind with the little girl, you said we were gonna to get the kind with the baby.' },
  { user: 3, text: 'No, you said the baby creeps you out.' },
  { user: 1, text: 'No, the little girl creeps me out.' },
  { user: 3, text: 'You said the baby.' },
  { user: 1, text: 'Why would the baby creep me out?' },
  { user: 3, text: 'Why would the little girl creep you out?' },
  { user: 1, text: 'This is going in your book?' },
  { user: 3, text: 'What?! Excuse me!' },
  { user: 0, text: ' Oh hi!' },
  { user: 0,
    text: 'Oh! Well let’s look for them.  Oh-oh-hey! Are these them?' },
  { user: 0, text: 'All right! ' },
  { user: 0, text: 'Oh good.' },
  { user: 0, text: ' Oh, wait! Sorry, Mr. Paul? Mr. Paul?' },
  { user: 0,
    text: 'Paul. Umm, I just wanted you to know that Ross really is a great guy.' },
  { user: 0,
    text: 'You just don’t look old enough to have a twenty-year-old daughter.' },
  { user: 0, text: 'Oh. We?' },
  { user: 0,
    text: 'Oh no! Yes! Of course, I know that! I just—I meant y’know are you still a ‘We’ or are you just ‘You?’' },
  { user: 0, text: ' Ohh. So you raised her all on your own?' },
  { user: 0, text: 'Ohh.  Ooh!' },
  { user: 1, text: 'Hey!' },
  { user: 3, text: 'How was your first day?' },
  { user: 1,
    text: 'Damn those robots, they’re supposed to be our faithful servants!' },
  { user: 2, text: 'Joey?!' },
  { user: 0, text: 'I was just getting him to like you.' },
  { user: 2, text: 'Joey?! Joey!! ' },
  { user: 0, text: 'Ross, Joey is not here.' },
  { user: 2, text: 'Okay, I’ll just wait for him in here!' },
  { user: 0, text: 'Ross, it’s okay. You can come out.' },
  { user: 2, text: ' Oh! Oh my God! I didn’t even see you!' },
  { user: 0, text: 'Bye!' },
  { user: 2,
    text: 'What-what-what the—how da-how did-what the-how did-what?!' },
  { user: 0,
    text: 'Well, y’know he lost his keys so he was looking for them…' },
  { user: 2, text: ' In your mouth?!' },
  { user: 0,
    text: 'No! Downstairs! And we got to talking y’know, for like two hours, and I really liked him so I invited him up here for a cup of coffee.' },
  { user: 2, text: 'You were at the coffeehouse!' },
  { user: 0,
    text: 'Ross, what’s the big deal? So I kissed the guy!' },
  { user: 2,
    text: 'He is my girlfriend’s father, okay? It’s-it’s, it’s weird!' },
  { user: 0, text: 'Wh—You dated my sister!' },
  { user: 2, text: 'That was different!' },
  { user: 0, text: 'What? Why?!' },
  { user: 2, text: 'This is weird for me!' },
  { user: 0,
    text: 'Ross look, look this is good for you. Okay? Let’s face it, so far the guy’s not lovin’ ya! But I can turn that around! I got the inside track! We can all go out to dinner, y’know? And I can talk you up! Ross, the guy is a very, very successful lawyer!' },
  { user: 2, text: 'How is that important?' },
  { user: 0, text: 'Oh it’s important!' },
  { user: 3,
    text: 'Well y’know Joey, you’re a pretty charming guy.' },
  { user: 3,
    text: 'No sweetie, you’ve got to win over the guy that controls C.H.E.E.S.E.! You’ve got to kiss some serious robot ass!' },
  { user: 1,
    text: 'So do you think uh, Joey’s more charming than me?' },
  { user: 3,
    text: 'Yeah! That’s why I’m sleeping with him on the side.' },
  { user: 1, text: 'Yeah, you wish. ' },
  { user: 3, text: 'Phoebe, stop writing about us!' },
  { user: 1, text: 'Who?' },
  { user: 3,
    text: 'Okay fine! Fine! Then you know what, I’ll just write about Phyllis! Hmm!' },
  { user: 1, text: 'Hmm.' },
  { user: 3, text: ' Phyllis is sitting in a chair.' },
  { user: 1, text: 'Oh.' },
  { user: 3, text: ' Phyllis sees what I’m doing.' },
  { user: 1, text: 'Oh-oh.' },
  { user: 0,
    text: 'So it seemed that my prom date had stood me up, so Ross selflessly, offered to take me.' },
  { user: 0,
    text: 'Wow! I definitely did not see that one backfiring! I’m gonna go to the bathroom.' },
  { user: 2, text: 'Yeah, take your time.' },
  { user: 2,
    text: ' Just-just so you know I was a freshman and she was a senior. So it wasn’t as bad as-as…' },
  { user: 2, text: 'Not all bad.' },
  { user: 2,
    text: 'Yeah. You know what? I know what you mean; I do that too.' },
  { user: 2,
    text: 'No! No! Not—I don’t mean I-I see her as a twelve-year-old girl! I mean I-I have a son, who’s umm six and I still think of him as a baby.' },
  { user: 2,
    text: 'Yeah, well my-my ex-wife and I share custody of Ben and umm, uh, and just so you know, Carol and I are on excellent terms as I’m sure you are with your wife!  It’s unbelievable!' },
  { user: 0,
    text: 'Oh we were, but that was just a , I mean that was just a big drunken mistake.' },
  { user: 2, text: 'You’re back.' },
  { user: 0,
    text: 'Oh! Whoops! I’m sorry, you were talking about Emily!' },
  { user: 3,
    text: 'Chandler, we said we would meet at the coffeehouse at six.' },
  { user: 1, text: 'We said seven!' },
  { user: 3, text: 'We said six!' },
  { user: 1,
    text: 'The only way that I said six would be if the seven’s, let meet at seven, not at six.' },
  { user: 3,
    text: 'Yeah and if I had seven, maybe I would’ve said something like this, "Wow! My boyfriend’s such a wise ass—seven!"' },
  { user: 1, text: 'Oh my good God.' },
  { user: 3, text: 'Ugh!' },
  { user: 1, text: 'What?!' },
  { user: 3, text: 'What time?' },
  { user: 1, text: ' What does it say?!' },
  { user: 1,
    text: 'Thank you for writing your book. Its-its uh, great book and you are the queen of everything.' },
  { user: 1, text: '' },
  { user: 1, text: 'So you knew we were gonna miss the movie!' },
  { user: 3,
    text: 'Inside of telling us you decided to write in your stupid book!' },
  { user: 1,
    text: 'Oh I’m so sorry man! Is there anything I can do?' },
  { user: 1, text: 'Hi, how are ya?' },
  { user: 1, text: ' The reason he just said.' },
  { user: 1, text: 'Yeah, I’ve been there my friend.' },
  { user: 0,
    text: 'I mean if you think about it, I mean Ross did learn something from each marriage.' },
  { user: 0,
    text: 'Now wait a minute that’s not fair. He was married to me a hell of a lot longer than he was married to Emily, he just didn’t tell me. ' },
  { user: 2,
    text: 'Y’know what? I-I-I… I-I have had enough of this! Y’know, I-I-I care a great deal about your daughter and I have treated her with nothing but respect! So if-if you’ve got a problem with me, frankly…' },
  { user: 2, text: 'God no!' },
  { user: 2,
    text: 'Well if it doesn’t matter to her, it doesn’t matter to me!  Still not yelling!' },
  { user: 2,
    text: 'That’s okay, I’m not so crazy about myself right now either.' },
  { user: 2, text: 'Uh yeah, I guess—Yeah! I guess so.' },
  { user: 2, text: 'Ohhh! Kids!' },
  { user: 0,
    text: ' Wait-wait-wait, I just thought of another story about how nice Ross is!' },
  { user: 2,
    text: 'That’s okay Rach, we’re not liking Ross right now.' },
  { user: 0, text: 'Oh! I’ve got a lot of those too!' } ];

$(document).ready(function(){
    //add our users to the conversation 
    addUsers();
    //start the conversation
    start(0);
});

function addUsers(){
    //user 1
    $.ajax({
        type: 'POST',
        url: '/user?pos=0&name=' + users[0] + '&theme=1'
    });
    //user 2
    $.ajax({
        type: 'POST',
        url: '/user?pos=1&name=' + users[1] + '&theme=2'
    });
    //user 3
    $.ajax({
        type: 'POST',
        url: '/user?pos=2&name=' + users[2] + '&theme=3'
    });
    //user 4
    $.ajax({
        type: 'POST',
        url: '/user?pos=3&name=' + users[3] + '&theme=4'
    });
}

function start(pos){
        if(pos >= script.length){
            console.log(pos);
            return;
        }
        $.ajax({
            type: 'POST',
            url: '/chat?pos=' + (script[pos].user) +
                 '&text='+encodeURIComponent(script[pos].text)
        });
        setTimeout(start(pos+1),10000000);
}
